### PR TITLE
[WIP] initial work on a new left-menu for global nav

### PR DESCRIPTION
**Pull request by jippi**
experimenting with global navigation to the right and other UX improvements

### CODE REVIEW

**Comment by multani** [comment]
@jippi Do you have a screenshot for this? :)

**Comment by jippi** [comment]
Completely WIP, https://monosnap.com/file/njeWo2z5R3uY5To6fIVfp3gN9aVm1p

**Comment by multani** [comment]
Neat!

**Comment by jippi** [comment]
Pushed some perf fixes to this branch too

**Pull request merged**
