### PR TITLE
Add Nomad 0.6 support (deployments, job versions)

### LINKED ISSUE #240: Stopping a job should redirect to /jobs route on success
Currently, it stays on the existing page, which may be misleading if you leave your computer and come back to it later.

### LINKED ISSUE #241: Refreshing a non-existent/stopped job results in empty jobs/view page
It should instead redirect to the /jobs/index route and potentially show an error.

### LINKED ISSUE #253: Jobs table is not correct
I installed hash-ui dashboard by running the docker image as an nomad job. Everything seems to be working, but I am running into a difference between hash-ui and the nomad cli when requesting the status of the job.

At this moment I have 2 jobs on my nomad cluster and the `webfiles` job in hash-ui stays in starting, when I check the status through the nomad cli, the status in the cli is running. I also checked docker and can confirm my job has started and works as expected.

Any idea if this is a bug or an error on my part somewhere?

screen shot 2017-06-05 at 09 31 12

```
nomad status webfiles
ID            = webfiles
Name          = webfiles
Type          = service
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
webfiles    0       0         1        0       0         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status   Created At
e88cce10  4cdb9a5c  f52194de  webfiles    run      running  06/05/17 08:58:29 CEST

nomad status dashboard
ID            = dashboard
Name          = dashboard
Type          = service
Priority      = 50
Datacenters   = dc1
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
dashboard   0       0         1        0       2         0

Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status    Created At
1669186d  415b6c00  f52194de  dashboard   run      running   06/03/17 17:42:08 CEST
047c7bf4  80a8ce68  f52194de  dashboard   stop     complete  06/03/17 16:59:17 CEST
da214e7d  8198b12d  f52194de  dashboard   stop     complete  06/03/17 16:06:34 CEST

```

### LINKED ISSUE #277: FEATURE: Display Nomad job deployment information
The release of Nomad 0.6.0 brings the feature of deployments, and it would be lovely to display information about a job deployment history/status alongside the job information.

Initial thinking could be that deployments are displayed in two ways:
1. The jobs list page a column could be added stating the last deployment status
2. The job details page could gain a deployment tab, which details deployment history

I would be happy to take a bash at this if you're happy with that @jippi and would love any and all feedback.

### LINKED ISSUE #281: allocation status colors don't show up in Firefox
Hashi-UI version: 0.14.0
OS: Windows 7 x64
Firefox version: 54.0.1
Vivaldi version: 1.10.867.48

* As seen in Firefox

image

* As seen in Vivaldi:

image

Regards,
Shantanu

P.S.
Do let me know if more info is needed.

### LINKED ISSUE #293: have job overview Allocation Status reflect latest deployment
When #277 is done, it would become possible to have a filter on the allocations used for the *Allocation Status* on the job overview page. This would then restrict the list of allocations to the latest deployment.

Currently, when doing lots of deploys, the *Allocation Status* bar gets filled up with failed and completed counts for allocations that have been replaced by others, in newer deployments.

### PR DESCRIPTION
**Pull request by jippi**
**This PR can be tested with docker image `jippi/hashi-ui:pr-295`**

- [x] List all deployments
- [x] Show Canary, Health and Placement statistics for deployments
- [x] Show raw deployment JSON payload
- [x] List deployments for a specific job
- [x] List allocations for a deployment
- [x] List and view a job at different versions
- [x] Filter deployment by ID, Job and Status
- [x] Fixed SVG progress bars in firefox
- [x] Special handling of Periodic and Parameterized jobs 
  - [x] Show jobs spawned by the parent job
  - [x] Easy navigation to the parent job 
  - [x] Allow triggering periodic job from the UI (upper right corner on a job page)
- [x] better and more consistent breadcrumbs for jobs, allocations and deployments
- [x] Allow promote, fail and pause of deployments

Closes #277
Closes #293 
Closes #281
Closes #253
Closes #241
Closes #240

### CODE REVIEW

**Comment by jippi** [comment]
This PR should be ~complete now - I'll merge it shortly, but would love some feedback on it

**Comment by hsmade** [comment]
Very happy with the info provided, and the colors. I still would like to have the data/time in there, which you can get through some small rabbit hole from the version.

**Comment by jippi** [comment]
@hsmade where would you like to see the date/time ? in the deployment lists? Currently tracking that in https://github.com/hashicorp/nomad/issues/3071

**Comment by hsmade** [comment]
Currently, you can (only) get the SubmitTime through /v1/job/<job>/versions

**Comment by hsmade** [comment]
As for where, I think the deployment over view would become too crowded, unless you link the version to a page about that (which opens up the possibility of doing a revert to an earlier version (nomad job revert <version>)). Another option is the deployment detail page.

**Pull request merged**
