### PR TITLE
fix Id to ID

### LINKED ISSUE #265: Job Top Bar is using Name not job Id
Our deployment mechanism creates a nicer name then the id when we upload.  This however breaks with the new changes to the jobTopBar that using the job.Name in the url.  The url is actually based on the Id.  This has probably not broken anyone else because they most likely have them as the same.

### PR DESCRIPTION
**Pull request by cross311**
fix #265

### CODE REVIEW

**Comment by cross311** [comment]
Deploying to our dev environment to test. please hold on merging.

**Comment by cross311** [comment]
fix #266.

**Comment by cross311** [comment]
Still waiting for it to deploy

**Comment by cross311** [comment]
Has been deployed to our dev env. and the links actually work now.  Thanks!

**Comment by jippi** [comment]
Thanks again :)

**Pull request merged**
