### PR TITLE
Add support for Consul ACL Token

### LINKED ISSUE #174: ACL Support for Consul UI
Hi,

thanks for the great job!

In release notes you mentioned that it's possible to request an ACL support for Consul UI - may I do that? :)

Thanks!

### PR DESCRIPTION
**Pull request by jippi**
Fixes #174

To test this PR please use:

` docker run --rm -e CONSUL_ENABLE=1 -e CONSUL_ACL_TOKEN=<token> -e CONSUL_ADDR=127.0.0.1:8500 jippi/hashi-ui:pr-175`

### CODE REVIEW

**Comment by jippi** [comment]
@ashald can you give this a spin? :)

**Comment by Ashald** [comment]
@jippi may I ask you to upload a build for linux? My Go is terrible and it takes me forever to build a thing with it. :)

**Comment by jippi** [comment]
@Ashald any way you can roll a docker version to test? otherwise I can try and build something out :)

**Comment by Ashald** [comment]
Unfortunately it's not possible to run docker in our environment. :(

Also, how do you think, is it possible to have ACL support in similar way to how it's done in Consul UI - in the sense that user can enter a token in the web UI and see only what is allowed for that token.

**Comment by jippi** [comment]
@Ashald I've considered the per-session token, though it works against some of the performance improvements i've done internally - is it a concrete case where everyone uses their own ACL token?

**Comment by jippi** [comment]
@Ashald a linux build can be found here: https://dl.dropboxusercontent.com/u/27514/hashi-ui-builds/pr-175-hashi-ui-linux-amd64

**Comment by Ashald** [comment]
Thanks for the build! I'll give it a try.

Yeah, we essentially have a token per "group"/"role"/"developer" (depending on circumstances) so everybody uses their own token to access Consul. That's mainly for securing KV store, disallowing modification of announced services and prepared queries along with modifying system settings of Consul and using _rexec.

**Comment by jippi** [comment]
@Ashald okay, interesting setup! :) maybe many people got their access like that as well.. i've never played with ACL and Consul, so don't got much experience with it at this time.

I can see why that would be the ideal way of doing things though

**Comment by Ashald** [comment]
👍

**Comment by jippi** [comment]
@Ashald did the PR build work ?

**Comment by jippi** [comment]
@Ashald bump? :)

**Comment by Ashald** [comment]
Sorry, didn't have time to check it so far. Will check later today.

**Comment by Ashald** [comment]
Just tested it and it doesn't work. :( I used a `management` ACL token (that is supposed to give access to all resources) but wasn't able to see restricted entries in KV. Let me know whether I can provide you some extra information for debug purposes.

**Comment by jippi** [comment]
@Ashald you couldn't see anything or only missing KVs ?

**Comment by Ashald** [comment]
@jippi it was as though no token was used.

Here is a log (rather short) that I recorded for starting a Hashi-UI and navigating to a dir `some-dir` in KV storage (`some-dir` is open for anonymous).

```
$ CONSUL_ACL_TOKEN="secret-token" ./pr-175-hashi-ui-linux-amd64 -consul.enable -consul.address "127.0.0.1:8500" -log-level debug
(114476) 2017/01/10 21:43:48.254352 {"level":"info","msg":"application created","context":{"app":"hashi-ui","enabled":false,"version":"1.5.0"}}
21:43:48.254 main.go:76 ▶ INFO  -----------------------------------------------------------------------------
21:43:48.254 main.go:77 ▶ INFO  |                             NOMAD UI                                      |
21:43:48.254 main.go:78 ▶ INFO  -----------------------------------------------------------------------------
21:43:48.254 main.go:79 ▶ INFO  | listen-address    : http://0.0.0.0:3000                                |
21:43:48.254 main.go:80 ▶ INFO  | proxy-address     :                                                    |
21:43:48.254 main.go:81 ▶ INFO  | log-level         : debug                                              |
21:43:48.254 main.go:89 ▶ INFO  | nomad.enable      : false                                              |
21:43:48.254 main.go:93 ▶ INFO  | nomad.read-only       : No (Hashi-UI can change Nomad state)               |
21:43:48.254 main.go:95 ▶ INFO  | nomad.address         : http://127.0.0.1:4646                              |
21:43:48.254 main.go:96 ▶ INFO  | nomad.ca_cert         :                                                    |
21:43:48.254 main.go:97 ▶ INFO  | nomad.client_cert     :                                                    |
21:43:48.254 main.go:98 ▶ INFO  | nomad.client_key      :                                                    |
21:43:48.254 main.go:101 ▶ INFO  | consul.enable        : true                                               |
21:43:48.254 main.go:105 ▶ INFO  | consul.read-only     : No (Hashi-UI can change Consul state)              |
21:43:48.254 main.go:107 ▶ INFO  | consul.address       : 127.0.0.1:8500                                     |
21:43:48.254 main.go:108 ▶ INFO  | consul.acl-token     : secret-token               |
21:43:48.254 main.go:110 ▶ INFO  -----------------------------------------------------------------------------
21:43:48.255 main.go:111 ▶ INFO
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc1
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc2
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc3
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc4
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc5
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 consul.go:26 ▶ INFO  Starting handlers for Consul DC: dc6
21:43:48.257 consul.go:40 ▶ INFO    -> Connecting to Consul
21:43:48.257 consul.go:49 ▶ INFO    -> Starting resource watchers
21:43:48.257 main.go:150 ▶ INFO  Consul client successfully initialized
21:43:48.258 main.go:206 ▶ INFO  Listening ...
21:43:48.263 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 2854690)
21:43:48.269 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 7044243)
21:43:48.269 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 2854690)
21:43:48.274 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 7044243)
21:43:48.278 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 5125003)
21:43:48.279 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 3748768)
21:43:48.281 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 5125003)
21:43:48.281 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 3748768)
21:43:48.299 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 8108172)
21:43:48.301 consul_region.go:121 ▶ DEBUG  Services index is changed (0 <> 8008980)
21:43:48.304 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 8108172)
21:43:48.306 consul_region.go:154 ▶ DEBUG  Nodes index is changed (0 <> 8008980)
21:43:53.288 main.go:145 ▶ INFO  Redirecting / to /consul
21:43:55.080 main.go:145 ▶ INFO  Redirecting / to /consul
21:43:55.548 consul_hub.go:71 ▶ ERROR  No region provided
21:43:55.586 consul_hub.go:110 ▶ WARNI  Ignoring unhandled message: FETCH_CONSUL_REGIONS (missing region)
21:43:55.586 consul_hub.go:112 ▶ DEBUG  Sending request for user to select a region in the UI again
21:43:55.586 consul_hub.go:110 ▶ WARNI  Ignoring unhandled message: FETCH_CONSUL_REGIONS (missing region)
21:43:55.586 consul_hub.go:112 ▶ DEBUG  Sending request for user to select a region in the UI again
21:43:56.187 consul_region.go:121 ▶ DEBUG  Services index is changed (7044243 <> 7044249)
21:43:56.192 consul_region.go:154 ▶ DEBUG  Nodes index is changed (7044243 <> 7044249)
21:43:59.307 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event FETCH_CONSUL_REGIONS (index 0)
21:43:59.307 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event WATCH_CONSUL_SERVICES (index 0)
21:43:59.307 consul_connection.go:70 ▶ DEBUG  [571bdca6] Sending our current services list
21:43:59.307 consul_connection.go:70 ▶ DEBUG  [571bdca6] Started watching services
21:44:00.718 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event UNWATCH_CONSUL_SERVICES (index 0)
21:44:00.718 consul_connection.go:70 ▶ DEBUG  [571bdca6] Removing subscription for services
21:44:00.746 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event WATCH_CONSUL_KV_PATH (index 0)
21:44:00.746 consul_connection.go:64 ▶ INFO  [571bdca6] Started watching consul/kv/path?/
21:44:04.262 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event UNWATCH_CONSUL_KV_PATH (index 0)
21:44:04.262 consul_connection.go:70 ▶ DEBUG  [571bdca6] Processing event WATCH_CONSUL_KV_PATH (index 0)
21:44:04.262 consul_connection.go:64 ▶ INFO  [571bdca6] Started watching consul/kv/path?some-dir/
21:44:07.922 consul_region.go:121 ▶ DEBUG  Services index is changed (8008980 <> 8008989)
21:44:07.930 consul_region.go:154 ▶ DEBUG  Nodes index is changed (8008980 <> 8008989)
```

**Comment by Ashald** [comment]
Let me know if you need another round of testing ;)

**Comment by jippi** [comment]
@Ashald it would be amazing if you could PR a nomad config file and ACL file i can use to test, I got 0 experience with Consul & ACL :) Adding a script ala https://github.com/jippi/hashi-ui/tree/master/scripts/mutli-region-cluster would make testing this so much more efficient :)

**Comment by jippi** [comment]
@Ashald i've updated the PR with a version of ACL that works for me (tm)

**Pull request merged**
