### PR TITLE
add linux-arm64 as build target

### PR DESCRIPTION
**Pull request by hsmade**
simulating the build in docker using ubuntu, seems to just work.
I can do a PR for a multi-arch docker image as well, if we want to.

### CODE REVIEW

**Comment by jlec** [comment]
LGTM

**Review by jippi — APPROVED** [review]

**Comment by jippi** [comment]
Thanks!

**Comment by analytically** [comment]
No binaries available for 1.3.9?

**Comment by hsmade** [comment]
@jippi can you check why there's no binaries at all for 1.3.9? Seems to be happening more often when I look at the history

**Pull request merged**
