### PR TITLE
Add TLS for nomad 

### LINKED ISSUE #166: TLS support
Hey,

The UI looks awesome! :) But does it support nomad when TLS is enabled? The readme only mentions NOMAD_ADDR while TLS support requires NOMAD_CACERT, NOMAD_CLIENT_CERT, and NOMAD_CLIENT_KEY

### PR DESCRIPTION
**Pull request by jippi**
fixes #166

### CODE REVIEW

**Comment by jippi** [comment]
@sheerun this PR can be tested with `jippi/hashi-ui:pr-167` docker image :)

**Comment by sheerun** [comment]
seems to work :) thank you!

**Comment by jippi** [comment]
@sheerun wow, that was easy then! :) thanks for testing

**Comment by jippi** [comment]
Tagged https://github.com/jippi/hashi-ui/releases/tag/v0.11.0 :)

**Pull request merged**
