### PR TITLE
adding AllowStale = true to the api QueryOptions

### PR DESCRIPTION
**Pull request by lolovarga**
PR to cover the issue described here: [https://github.com/jippi/hashi-ui/issues/238](url)

### CODE REVIEW

**Comment by jippi** [comment]
Hi @lolovarga - thanks for your first contribution :) 

Would it be possible to have it as a CLI flag rather than hardcoded? :)

CLI: `--nomad-allow-stale`
ENV: `NOMAD_ALLOW_STALE` 

Default value for the new value is `true`

**Comment by lolovarga** [comment]
adding:
CLI: --nomad-allow-stale
ENV: NOMAD_ALLOW_STALE
Default value is true

**Comment by jippi** [comment]
looks good @lolovarga - thanks for the quick fix! 

only thing missing i think is the README do document the new option, otherwise this is totally ready to be merged in :)

**Comment by jippi** [comment]
Perfect, thank you so much @lolovarga ! :)

**Pull request merged**
