### PR TITLE
Adding startLogging for nomad-skip-verify

### PR DESCRIPTION
**Pull request by sepulworld**

### CODE REVIEW

**Comment by jippi** [comment]
Ah yes :)

**Comment by sepulworld** [comment]
Sorry, just noticed I missed the option in the start up logging. I think all bases covered now.

**Comment by jippi** [comment]
Amazing - again thanks for the contribution ! :)

**Comment by sepulworld** [comment]
Thank you for the super solid hashi-ui! rocks! 👍

**Pull request merged**
