### PR TITLE
Replace restart with an update to meta, which forces a restart adhering to the update stanza

### PR DESCRIPTION
**Pull request by hsmade**
In the original restart code, we would stop and start a job. This change will use the built-in nomad mechanism to do a rolling restart, when the update stanza is configured.
It will also, like the previous code, force a start if the job was not running before, by setting job.Stop to false.

### CODE REVIEW

**Comment by hsmade** [comment]
@jippi what do you think about this?

**Comment by jippi** [comment]
i like it, but would prefer it being a new option (maybe make restart button a button-dropdown with the new option)

**Comment by hsmade** [comment]
I admit, I was lazy.

On Fri, Feb 9, 2018 at 11:03 AM, Christian Winther <notifications@github.com

**Comment by hsmade** [comment]
Hows this?

**Comment by hsmade** [comment]
sigh, let me re-PR this.. this is messy with that rebase

**Pull request closed without merging**
